eureka:
  
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: CLOUD-GATEWAY 
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      routes:
      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/products/**
 
        filters:
        - AuthenticationFilter
        metadata:
          cors:
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            maxAge: 30
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**    
        metadata:
          cors:
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            maxAge: 30


            
   
server:
  port: 8082
  