
spring:
  application:
    name: CLOUD-GATEWAY 
#  main:
#    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      routes:
      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/products/**
 
        filters:
        - AuthenticationFilter
        metadata:
          cors:
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            maxAge: 30
            
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**    
        metadata:
          cors:
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            maxAge: 30
            
      - id: WEBSOCKET
        uri: wss://api.play-real-tictactoe.cloud
        predicates:
         - Path=/api/**    
     

           
  